### ISSUE TITLE
[UX] Identify Icons, Applications, and UI

### ISSUE THREAD

**Issue by andrewsgreene** [defenseunicorns/baffles-api#11]
As a User, I want to view relevant applications, So that I effectively use the product.

## Acceptance Criteria

Given [Baffles Dashboard Design](https://drive.google.com/drive/folders/1sxxaM9UFQOUuKGTEdhxv-qXkhmiHO4mx?usp=sharing)
When I open the dashboard
Then relevant applications and their icons are displayed by default
And the applications are ordered in an optimal manner
And design files have been updated

**Comment by jacobgicker** [comment]
All icons that have been requested are available.
