### ISSUE TITLE
Create a Baffles CRD

### ISSUE THREAD

**Issue by andrewsgreene** [defenseunicorns/baffles-api#19]
[example](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)

Baffles can most easily identify a 'baffles application' with a custom resource.
The CRD should define:
- name
- description
- application icon
- url
- type: app or virtualmachine
- group: baffles.defenseunicorns.com

Baffles api helm chart should be updated to deploy a CRD
Docs should be updated as appropriate

**Comment by andrewsgreene** [comment]
good to know [helm crd](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/)

**Comment by runyontr** [comment]
Thinking about discoverability:  

Will baffles be able to show applications installer without a Baffles CRD installed onto the cluster, or will we have Zarf (or other tool) have to add that CR to the deployment for it to integrate with Baffles?

**Comment by TheFutonEng** [comment]
> Thinking about discoverability:
> 
> Will baffles be able to show applications installer without a Baffles CRD installed onto the cluster, or will we have Zarf (or other tool) have to add that CR to the deployment for it to integrate with Baffles?

@runyontr, the latter for now.  The CR will be required in order to integrate an application with Baffles.  We talked through what auto discovery would look like and it seemed like a substantial amount work around looping through all deployed services, figuring out if what is on the other side is a GUI that a user may want to interact with or just an API endpoint of something.  There's also some work around figuring out what icon to display for a discovered service once it's determined what exists on the other side of the service.  

Note, this is meant to be an MVP type of approach.  A for realsies auto discovery approach could be revisited as part of a future release.

**Comment by TheFutonEng** [comment]
Got a sample CRD stood written up in the 19-baffles-crd branch.

**Comment by TheFutonEng** [comment]
Example object:

```
[rmengert@Robs-MBP:~/projects/baffles-api/chart/crds]
$ kubectl describe appdata.baffles.defenseunicorns.com my-app-data 
Name:         my-app-data
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  baffles.defenseunicorns.com/v1
Kind:         AppData
Metadata:
  Creation Timestamp:  2022-09-16T21:46:13Z
  Generation:          1
  Managed Fields:
    API Version:  baffles.defenseunicorns.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:apptype:
        f:description:
        f:displayname:
        f:icon:
        f:url:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-09-16T21:46:13Z
  Resource Version:  2038
  UID:               9f1bda37-0d59-40b9-a511-1375d5d35da3
Spec:
  Apptype:      virtualmachine
  Description:  Matlab VM
  Displayname:  matlab
  Icon:         /path/to/icon/icon.svg
  URL:          /vnc/vnc_lite.html?path=api/v1/vmi/${namespace}/${b}/vnc
Events:         <none>
[rmengert@Robs-MBP:~/projects/baffles-api/chart/crds]
$ 
```

**Comment by TheFutonEng** [comment]
Pushed the CRD up, pending PR to see if anything else is going to be needed in the CRD from other conversations happening (possibly namespace).

**Comment by TheFutonEng** [comment]
Nevermind, will open a PR as a draft.
